### ISSUE TITLE
The documentation page is a bit buggy

### ISSUE THREAD

**Issue by vlsts** [Shroud-email/website#2]
Hi there! I found some issues while browsing the documentation so I decided to make this issue. They are:

- When you first go to the documentation page from the landing page the theming is broken and there is no light / dark mode icon appearing in the icon which is supposed to change the theme (After you refresh the documentation page the theming works as it should and it shows the specific theme icon in the button)
- The theme button is duplicated, the first one works while the second one doesn't
- The log in button is duplicated, both of them work.

I tested this on both Firefox v102.0 and Brave v1.40.109 w/ Chromium 103.0.5060.66 on W11 and I had the same results.

I tried showing these points in this GIF:
![gif](https://user-images.githubusercontent.com/26856087/177008108-1c839895-0b92-4c61-a929-08e1d20c2325.gif)

**Comment by taobojlen** [comment]
Hi, thanks for the detailed bug report and the GIF! It's much appreciated.

I've fixed the duplicates in the nav bar, and I've removed the light/dark theme selector for now. The theme will still follow your browser's preference, but it was a bit of a faff getting it working for now!
